export { HippoClient } from "./client.js";
export {
  HippoError,
  AuthenticationError,
  ForbiddenError,
  RateLimitError,
} from "./errors.js";
export { findSubject, factsAbout, isDuplicate, failures } from "./helpers.js";
export type {
  AskRequest,
  AskResponse,
  AuditEntry,
  AuditResponse,
  BatchRememberResult,
  ContextFact,
  ContextRequest,
  ContextResponse,
  CorrectRequest,
  CorrectResponse,
  CreateKeyRequest,
  CreateKeyResponse,
  CreateUserRequest,
  CreateUserResponse,
  DreamReport,
  EventsOptions,
  GraphEvent,
  GraphsListResponse,
  HealthResponse,
  HippoClientOptions,
  KeySummary,
  ListKeysResponse,
  ListUsersResponse,
  LlmUsage,
  OpExecutionTrace,
  OnRequestHook,
  OnResponseHook,
  RememberBatchRequest,
  RememberBatchResponse,
  RememberRequest,
  RememberResponse,
  RememberTrace,
  RetractRequest,
  RetractResponse,
  ScoringParams,
  UserSummary,
} from "./models.js";
