export { HippoClient } from "./client.js";
export {
  HippoError,
  AuthenticationError,
  ForbiddenError,
  RateLimitError,
} from "./errors.js";
export { findNode, factsAbout, isDuplicate, failures } from "./helpers.js";
export type {
  AskRequest,
  AskResponse,
  BatchResult,
  ContextRequest,
  ContextResponse,
  CorrectRequest,
  CorrectResponse,
  CreateKeyRequest,
  CreateKeyResponse,
  CreateUserRequest,
  CreateUserResponse,
  DreamReport,
  EventsOptions,
  Fact,
  GraphEdge,
  GraphEvent,
  GraphNode,
  HealthResponse,
  HippoClientOptions,
  KeySummary,
  ListKeysResponse,
  ListUsersResponse,
  OnRequestHook,
  OnResponseHook,
  RememberBatchRequest,
  RememberBatchResponse,
  RememberRequest,
  RememberResponse,
  RetractRequest,
  RetractResponse,
  TraceInfo,
  UsageInfo,
  UserSummary,
} from "./models.js";
